development:
  secret_key_base: 'use "rake secret" to generate a secret token and paste it here'

test:
  secret_key_base: 'use "rake secret" to generate a secret token and paste it here'

production:
  secret_key_base: 'use "rake secret" to generate a secret token and paste it here'
