membership:
  kinds:
    - premium
    - plus
    - reader

member:
  kinds:
    - person
    - family
    - organization
  genders:
    - male
    - female
    - n/a
  age_groups:
    - teen
    - young
    - middle
    - senior
    - n/a

category:
  kinds:
    - arts
    - biographies
    - business
    - children
    - comics
    - computers
    - cooking
    - crafts
    - engineering
    - entertainment
    - health
    - history
    - humour
    - law
    - literature
    - mathematics
    - medicine
    - news
    - others
    - reference
    - relationships
    - religion
    - politics
    - science
    - self-help
    - sports
    - travel

creator:
  kinds:
    - author
    - artist
    - publisher
    - vendor

item:
  kinds:
    - book
    - periodical
    - magazine
    - newspaper
    - compact_disc
    - dvd
  formats:
    - paperback
    - hardbound
    - cased
  length_uoms:
    - pages
    - minutes
  languages:
    - malayalam
    - english
    - hindi
    - tamil
    - kannada
    - arabic
    - other
  rights:
    - copyrighted
    - copyright_expired
    - patented
    - authors_rights
    - creative_commons
    - orphan_works
    - public_domain
  ratings:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10

item_creator:
  roles:
    - author
    - actor
    - director
    - editor
    - performer
    - producer
    - translator

copy:
  qualities:
    - new
    - used
    - worn_out
    - damaged
  statuses:
    - available
    - misplaced
    - lost
    - unavailable

issue:
  defaults:
    period: 7

format:
  date: 'yyyy-mm-dd'
